setup posts
FeshchenkoMaksym/blog pull request #3
Opened 2018-10-15 18:43 UTC by FeshchenkoMaksym

Add posts controller width one index action; 
Add model post with title text author; 
Add index view with simple list of post; 
Add post factory; 
Add rspec test for index action.

2018-10-15 18:51 UTC, Vitaliy-Maznyi commented on app/assets/javascripts/posts.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
please remove this file

2018-10-15 20:04 UTC, Vitaliy-Maznyi requested changes

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on app/assets/stylesheets/posts.scss
> +// Place all the styles related to the Posts controller here.
please remove this file

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on app/controllers/posts_controller.rb
> +    @posts = Post.find(params[:id])
this is show action for one post so here is more preferable to use instance name in singular, like `@post`

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on app/controllers/posts_controller.rb
> +    @post.save
if post saving fails because of validation or other errors it will redirect_ to show page so you won't be able to handle error and show message for user.

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on app/helpers/posts_helper.rb
> +module PostsHelper
we don't need for now this file so please remove it

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on app/models/post.rb
> +class Post < ApplicationRecord
please add validations:
- title, text and author should be present
- title shouldn't be less than 3 and more than 30 symbols
- text should be less than 3 symbols
- add custom error messages for all of the validations

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on app/views/posts/index.html.erb
> + <h1> Lisitng posts</h1>
Listing* typo

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on spec/support/factory_bot.rb
> +end
please add new line

2018-10-15 20:04 UTC, Vitaliy-Maznyi commented on spec/models/post_spec.rb
> +require 'rails_helper'
you don't need this file for now

2018-10-15 20:13 UTC, Vitaliy-Maznyi requested changes
please fix the review comments

2018-10-23 19:17 UTC, Vitaliy-Maznyi requested changes

2018-10-23 19:17 UTC, Vitaliy-Maznyi commented on spec/controllers/posts_controller_spec.rb
> +
https://github.com/everydayrails/rails-4-1-rspec-3-0/issues/36

2018-10-31 10:14 UTC, FeshchenkoMaksym commented
Ready

2018-10-31 10:23 UTC, Vitaliy-Maznyi requested changes
almost done, good job!

2018-10-31 10:23 UTC, Vitaliy-Maznyi commented on package.json
> +  "name": 'blog',
you don't need to change this file, please revert the changes and add it to exclusions in Rubocop

2018-10-31 10:23 UTC, Vitaliy-Maznyi commented on test/application_system_test_case.rb
> -require "test_helper"
you don't need this folder at all because we use Rspec for testing. So you can simply remove the `test` folder

2018-10-31 11:18 UTC, Vitaliy-Maznyi commented on spec/models/post_spec.rb
> +  describe 'when author is not present' do
`describe` should be used for describing classed and methods. And `context` for describing situations
For example: 
```
Describe Post, type: :model do
  describe '#archive' do
     context 'when post is already archived' do
        it 'returns message' do
           expect(something).to eq(something)
        end
     end

    context 'when post is not archived' do
        it 'archives post' do
           expect(post).to be archived
        end
     end
  end
end
```

so change `describe` to `context` here and below

2018-10-31 11:32 UTC, Vitaliy-Maznyi approved these changes
👍 you are good to merge!

2018-10-31 11:37 UTC, merged