update layout, slim, bootstrap 4
FeshchenkoMaksym/blog pull request #4
Opened 2018-11-06 19:26 UTC by FeshchenkoMaksym

update layout using slim;
setup bootstrap 4;
add design to the list of posts:

2018-11-06 19:30 UTC, FeshchenkoMaksym commented
![screenshot](https://user-images.githubusercontent.com/6437175/48088616-22bb0680-e20b-11e8-9aa8-d61c8d7658fc.png)

2018-12-13 19:28 UTC, FeshchenkoMaksym commented
![scren](https://user-images.githubusercontent.com/6437175/49962462-fedf9480-ff1d-11e8-8361-58b708743ade.png)
visual update

2019-01-14 18:21 UTC, Vitaliy-Maznyi requested changes
almost done. Remove the sizes.scss file, you don't need it for now, I'll explain you later where and how it should be used.

2019-01-14 18:21 UTC, Vitaliy-Maznyi commented on app/assets/stylesheets/layout/header.scss
> +    margin-top: 1.4em;
why do you need this margin-top here?

2019-01-14 18:21 UTC, Vitaliy-Maznyi commented on app/assets/stylesheets/shared/sizes.scss
> +$padding_topic_posts: 8px 16px 8px 16px;
you don't need to save all of the sizes inside the variables. Set this padding directly in the class where you've used this variable and remove this variable and the variable below

2019-01-15 11:10 UTC, FeshchenkoMaksym commented
![123](https://user-images.githubusercontent.com/6437175/51176860-b887a780-18c6-11e9-8dad-07e78be3ac80.png)

2019-01-15 11:19 UTC, Vitaliy-Maznyi approved these changes
let's merge

2019-01-15 11:21 UTC, merged